### ISSUE TITLE
release TODO list

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-rest#12]
# Context

What remains to do for the release.

# Decision

- [x] Wrap up the Docker documentation and docker-compose file
- [x] Update API Version doc for explorer-api to 2.0.0
- [x] Have some "How To Use" instructions in the README / Wiki
- [x] Cleanup submit-api README

# Acceptance Criteria

---

# Development 

# QA
